---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuanc.
--- DateTime: 2020/2/1 下午3:32
--- Description: 推送任务
---

local waitingKey = KEYS[1]
local detailKey = KEYS[2]

local minScore = ARGV[1]
local maxScore = ARGV[2]
local offset = ARGV[3]
local limit = ARGV[4]

local status, type = next(redis.call('TYPE', waitingKey))
if status ~= nil and status == 'ok' then
    if type == 'zset' then
        local list = redis.call('ZREVRANGEBYSCORE', waitingKey, maxScore, minScore, 'LIMIT', offset, limit)
        if list ~= nil and #list > 0 then
            -- 从等待队列中删除
            redis.call('ZREM', waitingKey, unpack(list))
            -- 获取任务信息
            local result = redis.call('HMGET', detailKey, unpack(list))
            -- 移除任务
            redis.call('HDEL', detailKey, unpack(list))
            return result
        end
    end
end
return nil
